### ISSUE TITLE
Type Mismatch: String Given

### ISSUE THREAD

**Issue by pitosalas** [troessner/reek#1058]
Here's the exception from Reek:

```
!!!
      Source /dropbox/cosi105b_jramirez/pa-ims/artist.rb can not be processed by Reek.
      This is most likely a Reek bug.
      It would be great if you could report this back to the Reek team
      by opening up a corresponding issue at https://github.com/troessner/reek/issues
      Make sure to include the source in question, the Reek version
      and the original exception below.

      Original exception:
      #<TypeError: type mismatch: String given>
      !!!
```

Here's the .reek file:

```yaml
---
IrresponsibleModule:
  enabled: false
InstanceVariableAssumption:
  enabled: false
DuplicateMethodCall:
  enabled: false
FeatureEnvy:
  enabled: false
TooManyStatements:
  enabled: true
  max_statements: 12
ControlParameter:
  enabled: false
UncommunicativeVariableName:
  enabled: true
TooManyInstanceVariables:
  enabled: true
TooManyMethods:
  enabled: true
UncommunicativeVariableName:
  reject: [/^.$/]
```

and Here's the source file

```Ruby
require 'minitest/autorun'
require './playlist'

class Playlist_Test < Minitest::Test

  def setup
    @playlist = Playlist.new
    artist1 = Artist.new("Blur")
    artist2 = Artist.new("Oasis")
    @playlist.add_artist(artist1)
    @playlist.add_artist(artist2)

    @playlist.add_track("Coffee and TV", "b")
    @playlist.add_track("Don't Look Back In Anger", "o")
  end

  def test_tracks
    assert_equal ["Coffee and TV", "Don't Look Back In Anger"],
    @playlist.track_names
  end

  def test_artists
    assert_equal ["Blur", "Oasis"], @playlist.artist_names
  end

  def test_count_tracks
    assert_equal 1, @playlist.count_tracks("b")
  end
end

```

**Comment by troessner** [comment]
Off topic: You can use [github flavored markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) in github issues, please use that for further issues to improve the readability. I just went ahead and updated your content above.

On topic!

The problem is in your configuration file. You are using "reject" as the last attribute which is an invalid identifier. As you can see in our [basic smell options](https://github.com/troessner/reek/blob/master/docs/Basic-Smell-Options.md) it should be "exclude".

Good thing you reported this though since this made me realize that the way we catch exceptions in our smell detectors actually masks errors users might make in Reeks configuration.

We should definitely fix this by validating the configuration in total before executing any smell detectors
cc @waldyr @mvz

**Comment by pitosalas** [comment]
Thanks. I think I may have found an error in your doc then:

https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md <https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Variable-Name.md>

— Pito

**Comment by troessner** [comment]
No, you're right, my bad!

"reject" does work indeed, I think you just need to use it differently.

Looking at the [defaults.reek](https://github.com/troessner/reek/blob/master/defaults.reek) you can see this for UncommunicativeVariableName:

```yaml
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept:
  - _
```

So using "reject" like above should work. 
However, as you can see, we already have 

```yaml
   - !ruby/regexp /^.$/
```

so this shouldn't be needed on your side.

**Comment by pitosalas** [comment]
Thanks… Maybe include a proper example in the doc that reflects the exact syntax.

What I was trying to do was to allow variables ending with a number. I think there are lots of legitimate reasons for that and don’t want to call it out.

Can you give me the proper syntax for that?

Thanks.

Pito

**Comment by troessner** [comment]
I looked into it and it seems like you uncovered a bug- please see #1063 for details. 

So 

```yaml
---
UncommunicativeVariableName:
  accept:
  - /\d+$/
```

would have been the right way and it will after the bugfix ;)
To deal with this now I'm afraid you'll need to explicitly whitelist variable names like this:

```yaml
---
UncommunicativeVariableName:
  accept:
  - x1
```
