### ISSUE TITLE
reek/spec rspec helper not picking up config.reek

### ISSUE THREAD

**Issue by prpetten** [troessner/reek#1093]
I tested with the following in `config.reek` file in my home directory.

``` yaml

---
"app/controllers":
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  UnusedPrivateMethod:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
"app/helpers":
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    enabled: false
exclude_paths:
  - db
  - config
```

Then in my rails_helper.rb

``` ruby
require 'reek/spec'
```

Then in my `spec/smells/reek_spec.rb` file

``` ruby
require 'rails_helper'

describe 'Code Smells' do
  # Check all ruby files in lib and app directory
  file_patterns = { lib: 'lib/**/*.rb', app: 'app/**/*.rb' }
  file_patterns.each do |directory, file_pattern|

    # within the context of given directory
    context "with #{directory}/ files" do
      Pathname.glob(file_pattern).sort.each do |file|

        # Execute smell check for each file
        context "with #{file} file" do
          it 'contains no code smells' do
            expect(file).not_to reek
          end
        end
      end
    end
  end
end
```

When I run my specs, I get a failure:

``` Shell
$ rspec spec/smells/reek_spec.rb
Failures: 
  1) Sniff Tests with app/ files with app/controllers/foo_bars_controller.rb file contains no code smells
     Failure/Error: expect(file).not_to reek

       Expected no smells, but got:
         InstanceVariableAssumption: FooBarsController assumes too much for instance variable '@foobar'
```

However when I run reek at the command line, I get no errors.

``` Shell
$ reek
0 total warnings
```
