### ISSUE TITLE
Support a reek configuration file with multiple yaml documents

### ISSUE THREAD

**Issue by IanWhitney** [troessner/reek#1208]
I noticed that this config.reek file didn't behave as I expected

```yaml
---
exclude_paths:
  - test

exclude_paths:
  - lib/legacy
```

This is because a single yaml document can't have duplicate keys, which I didn't know until now. 

But a yaml file can contain multiple documents, each of which can contain the same key

```yaml
---
exclude_paths:
  - test
---
exclude_paths:
  - lib/legacy
```

The [code that parses the yaml](https://github.com/troessner/reek/blob/58bb1ff752ed68b6fd3bb5d56a4de43d14c8707a/lib/reek/configuration/configuration_file_finder.rb#L66) uses `load_file` which only loads the first document. Other yaml methods, such as `parse_stream` can return an array of the yaml documents, which could then be merged into a single document.

This comes up for us because we use [a tool](https://github.com/umn-asr/reekup/) (still under development) that concatenates our 'standard' Reek config with a project-specific Reek config so that we don't run into problems having too many Reek config files. Each file could define an `excludes_path` setting.
