### ISSUE TITLE
Use strings not regexes in our configuration file.

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1321]
Coming from #1317  I suggest to drop the ruby specific extensions to yaml. 
This would mean to do this:

```yaml
UncommunicativeParameterName:
  reject:
  - foo
  - bar
```

rather than this:

```yaml
UncommunicativeParameterName:
  reject:
  - !ruby/regexp /foo/
  - !ruby/regexp /bar/
```

Turns out the necessary changes to our codebase are quite minimal, see the linked PR.
