### ISSUE TITLE
Scope detectors under "detectors"

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1358]
In analoy to our recent "scope directory directives under 'directories'" I'd like to propose a similar initiative for detectors, so:

```Yaml
detectors:
  Attribute:
    enabled: false

"web_app/app/controllers":
  NestedIterators: 
    enabled: false

exclude_paths:
  - lib/rake/legacy_tasks
```

Reasons are three fold:

1.) It will make our life significant easier when adding a schema validation.
2.) It increases consistency  since we treat directories and exclude_paths like that already.
3.) It encourages more structure since you are now forced to put detectors together thus increasing cohesion.

With Reek 5 at our doorstep now seems like a perfect time.

What do you think?
