### ISSUE TITLE
Converting strings to regexes with our new syntax is not working for directory directives

### ISSUE THREAD

**Issue by troessner** [troessner/reek#1377]
This will work:

```Yaml
---
detectors:
  UnusedPrivateMethod:
    exclude:
      - "/exclude regexp/"
```

but this won't:

```Yaml
---
directories:
  "app/controllers":
    UnusedPrivateMethod:
      exclude:
        - "/exclude regexp/"
```
Pull request incoming.
