### ISSUE TITLE
Reek using default config instead of .reek.yml file on codeclimate

### ISSUE THREAD

**Issue by brunossilveira** [troessner/reek#1409]
I'm running reek on my repository with a custom `.reek.yml` file. If I run reek locally everything works fine, but when on codeclimate it's not picking up the config file.

I talked to support team at codeclimate and they verified that this is in fact happening and it was not something wrong that I was doing. They also asked me to open this issue, so here I am.

I'm not entirely sure what more information I need to provide, so I'm sorry if something is missing.

Rails: 5.1.6
Ruby: 2.3.5

And this is my config file:

```
---
detectors:
  Attribute:
    enabled: true
    exclude: []
  BooleanParameter:
    enabled: true
    exclude: []
  ClassVariable:
    enabled: true
    exclude: []
  ControlParameter:
    enabled: true
    exclude: []
  DataClump:
    enabled: true
    exclude: []
    max_copies: 2
    min_clump_size: 2
  DuplicateMethodCall:
    enabled: true
    exclude: []
    max_calls: 1
    allow_calls: []
  FeatureEnvy:
    enabled: true
    exclude: []
  InstanceVariableAssumption:
    enabled: true
    exclude: []
  IrresponsibleModule:
    enabled: false
    exclude: []
  LongParameterList:
    enabled: true
    exclude: []
    max_params: 3
    overrides:
      initialize:
        max_params: 5
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 3
  ManualDispatch:
    enabled: true
    exclude: []
  MissingSafeMethod:
    enabled: true
    exclude: []
  ModuleInitialize:
    enabled: true
    exclude: []
  NestedIterators:
    enabled: true
    exclude: []
    max_allowed_nesting: 1
    ignore_iterators:
    - tap
  NilCheck:
    enabled: true
    exclude: []
  RepeatedConditional:
    enabled: true
    exclude: []
    max_ifs: 2
  SubclassedFromCoreClass:
    enabled: true
    exclude: []
  TooManyConstants:
    enabled: true
    exclude: []
    max_constants: 5
  TooManyInstanceVariables:
    enabled: true
    exclude: []
    max_instance_variables: 4
  TooManyMethods:
    enabled: true
    exclude: []
    max_methods: 15
  TooManyStatements:
    enabled: true
    exclude:
    - initialize
    max_statements: 5
  UncommunicativeMethodName:
    enabled: true
    exclude: []
    reject:
    - "/^[a-z]$/"
    - "/[0-9]$/"
    - "/[A-Z]/"
    accept: []
  UncommunicativeModuleName:
    enabled: true
    exclude: []
    accept:
    - "/V2$/"
    reject:
    - "/^.$/"
    - "/[0-9]$/"
  UncommunicativeParameterName:
    enabled: true
    exclude: []
    reject:
    - "/^.$/"
    - "/[0-9]$/"
    - "/[A-Z]/"
    - "/^_/"
    accept: []
  UncommunicativeVariableName:
    enabled: true
    exclude: []
    reject:
    - "/^.$/"
    - "/[0-9]$/"
    - "/[A-Z]/"
    accept:
    - "/^_$/"
  UnusedParameters:
    enabled: true
    exclude: []
  UnusedPrivateMethod:
    enabled: false
    exclude: []
  UtilityFunction:
    enabled: true
    exclude:
    - "/.#resolve$/"
    public_methods_only: false

exclude_paths:
  - db/
```

**Comment by troessner** [comment]
@brunossilveira thanks for your report
@mvz I'm still busy with #1406, do you have time to take this over? If not I can look into it next week.

**Comment by mvz** [comment]
@troessner sure!

@brunossilveira codeclimate is probably not using Reek 5 yet, since [their image](https://hub.docker.com/r/codeclimate/codeclimate-reek/) was last updated 3 months ago. Since you're already in contact with them, it's probable simplest if you ask them to update. If that doesn't work out I'll open a ticket myself.

**Comment by brunossilveira** [comment]
Thank you for the feedback @mvz! I will ask them to do that and if that works I can close this ticket.

**Comment by efueger** [comment]
Emily here from Code Climate Support - thanks for pointing that out @mvz 👍 
- We updated the image and @brunossilveira reports that it's working now.

**Comment by troessner** [comment]
Great, thanks for the update @efueger :)

**Comment by andreheijstek** [comment]
I'm having this problem when running reek via overcommit. I am using reek 5.3.1
The specific problem is that it ignores the exclude_path db, so I am getting lots of warnings on my migrations which I want to ignore.
Here's my .reek.yml
```
exclude_paths:
  - db
  - vendor
  - public
  - lib

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    FeatureEnvy:
      enabled: false

```
