### ISSUE TITLE
Reek config inheritance

### ISSUE THREAD

**Issue by dimitrovv** [troessner/reek#1434]
I've played a bit with the reek configuration and noticed it does not support config inheritance.
We've several projects, which have almost the same reek configuration with some exceptions/customization.

It'd be good to inherit the reek configuration from another reek config and override it then to DRY it etc.

It could be smth like that

* `ancestor/.reek.yml`

```yml
---
### Generic smell configuration
detectors:
  Attribute:
    enabled: true
    exclude: []
  BooleanParameter:
    enabled: true
    exclude: []
  ClassVariable:
    enabled: true
    exclude: []
  ControlParameter:
    enabled: true
    exclude: []
  MissingSafeMethod:
    enabled: false
### Directory specific configuration
directories:
  "app/controllers":
...
```

* `descendant/.reek.yml`

```yml
<%= IO.read('ancestors/.reek.yml') %>

detectors:
  MissingSafeMethod:
    enabled: true
```

----------------

This could be done by changing the way how the reek configuration is loaded in [ConfigurationFileFinder#load_from_file](https://github.com/troessner/reek/blob/v5.2.0/lib/reek/configuration/configuration_file_finder.rb#L60)

```ruby
configuration = YAML.load_file(path) || {}
```

->

```ruby
configuration = YAML.load(ERB.new(File.read(path)).result)
```
 
--------------

I'd like to PR this because we actively use reek and need this inheritance. What do you guys @troessner @mvz think of this?
