### ISSUE TITLE
Reek.yml is not correctly processed when run via overcommit #622

### ISSUE THREAD

**Issue by andreheijstek** [troessner/reek#1459]
I have reported this issue already at Overcommit, but they think it's a Reek issue. See https://github.com/brigade/overcommit/issues/622
Below the text of the issue again:

I'm having this problem when running reek via overcommit. I am using reek 5.3.1 and overcommit 0.46.0
The specific problem is that it ignores the exclude_path db, so I am getting lots of warnings on my migrations which I want to ignore.
Here's my .reek.yml

```
exclude_paths:
  - db
  - vendor
  - public
  - lib

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    FeatureEnvy:
      enabled: false
```
