### ISSUE TITLE
Directory configurations changed incompatibly in v5.4.0

### ISSUE THREAD

**Issue by rasaffie** [troessner/reek#1482]
When updating from `v5.3.2` to `v5.4.0` running `reek` from _CLI_ and  _Rake::Task_ has different outcomes:

<img width="1274" alt="Screen Shot 2019-06-04 at 12 09 08 PM" src="https://user-images.githubusercontent.com/5222997/58895354-b2e9fd00-86c1-11e9-9bec-5b8229c3a20e.png">

My rake configuration is:
```ruby
Reek::Rake::Task.new do |t|
  t.config_file   = '.reek.yml'
  t.source_files  = FileList['./**/*.rb'].exclude('./vendor/**/*.rb')
end
```

The problem is that the rake task finds the configuration file (changing its name causes a "file not found" error), but doesn't consider the directories rules, like:
```yml
directories:
  "db/migrate":
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
    TooManyStatements:
      enabled: false
```
