### ISSUE TITLE
directories in config relative to cwd, not to configuration file itself.

### ISSUE THREAD

**Issue by leonelgalan** [troessner/reek#1486]
## Setup

Rails app, where helpers smell of _UtilityFunction_

### _.reek.yml_
```yml
directories:
  "app/helpers":
    UtilityFunction:
      enabled: false
```

### _app/helpers/foo_helper.rb_
```ruby
module FooHelper
  def smelly_method(bar)
    bar.presence
  end
end
```

## Happy Path

```sh
reek --show-configuration-path app/helpers/foo_helper.rb
```

```
Using '.reek.yml' as configuration file.
Inspecting 1 file(s):
.
```

## Possible Bug

When linting through atom-linter, the current working directory (cwd) is set to the one the file being linted exists, in this case: _app/helpers_. Reek will still find the correct _.reek.yml_ from it's ancestors, first in _app_ and ultimately on the project's root. But, it won't match the directory `"app/helpers"`, because it's looking for `"app/helpers"` relative to the **cwd**  instead of relative to the configuration file.

```sh
cd app/helpers
reek --show-configuration-path foo_helper.rb
```

```
Using '../../.reek.yml' as configuration file.
Inspecting 1 file(s):
S

foo_helper.rb -- 1 warning:
  [5]:UtilityFunction: FooHelper#smelly_method doesn't depend on instance state (maybe move it to another class?) [https://github.com/troessner/reek/blob/v5.4.0/docs/Utility-Function.md]
```

I'm on **reek 5.4.0**

**Comment by Mozart2234** [comment]
Hi, you can try in.

**.reek.yml**

```yml
directories:
  "./app/helpers":
    UtilityFunction:
      enabled: false
```

This solution it worked for me.
