### ISSUE TITLE
Relative paths in .reek.yml directories section do not match to absolute paths

### ISSUE THREAD

**Issue by maximpertsov** [troessner/reek#1540]
When I run reek via overcommit, it does not honor custom configurations in the `directories` section of my `.reek.yml` file. After debugging the issue a bit, I found that the problems stems from the fact that overcommit passes in absolute directory paths, which do not resolve to the relative paths in `directories`.

For example, here is a part of my `.reek.yml` configuration:
```yaml
directories:
  "app/controllers/api/v1":
    UncommunicativeModuleName:
      enabled: false
```

Reek works correctly when I run `bundle exec reek`. However, when I run the command via overcommit, it reports linting errors that should have been disabled through my `directories` configuration.

However, reek via overcommit works correctly if I change my `directories` configuration to use absolute directory paths like so:
```yaml
directories:
  "<PWD>/app/controllers/api/v1":
    UncommunicativeModuleName:
      enabled: false
```
