### ISSUE TITLE
Rethinking configuration in reek

### ISSUE THREAD

**Issue by troessner** [troessner/reek#351]
Today I started working on https://github.com/troessner/reek/issues/349.

My first approach was to just add the "exclude" settings to our existing configuration file mechanism but pretty soon I realized that this wouldn't work like that: The configuration files only get read in after  we have build up the path tree which we intend to scan.
The reason for is that we have this fancy feature that you can just put whatever.reek in any source code directory and it kind of overlays whatever you configured before.
After realizing that, I thought of some unique, global configuration file at the top level just for configuration values like exlude directives which would get read in on reek start up.
This would work probably, but then we would be very inconsistent and overall this whole configuration loading mechanism would be even more obscure than before.

Making one step back I come to think that the real problem here is our configuration loading mechanism. 

**It's certainly nice to have, no question, but:**
- It adds a lot of complexity to the reek source code
- It adds a lot of complexity to the user interface not to mention that it's very hard to see what's going on and why.
- And my biggest point: I'm fairly certain that no "normal" reek user uses it. First of all it was (and still is) not properly documented, so the only way to even know this would be by accident. Second of all, even the reek users that I know personally don't use overlapping files at all, left alone files in multiple directories. I bet that 99% of all reek users have one file, and one file only in their root directory. This file is named settings.reek and looks like this (real life example from a commercial project that uses reek for their CI build):

``` Yaml
IrresponsibleModule:
  enabled: false
NestedIterators:
  exclude:
    - "ActiveModelErrorAdder#self.run" # should be refactored
    - "BookingRequests::Transfer#remote_validation"
    - "BookingRequestsController#vehicle_options" # respond_to block
    - "Content::Base#self.expose_fields" # unavoidable due to metaprogramming
NilCheck:
  exclude:
      - "Login#valid?"
```

Of course that's just assumption, but I believe that this feature is at least partially over-engineering.

**So here's my suggestion:**
- We get rid of this whole mechanism
- There's just one configuration file possible which must be defined at the top level
- This file get's read in on start-up

Plain & simple.

What do you think?
