### ISSUE TITLE
possible to set folder in config.reek ?

### ISSUE THREAD

**Issue by tansaku** [troessner/reek#408]
Hey, reek is totally awesome.

I'm just getting set up with a config.reek file like so:

```yml
IrresponsibleModule:
  enabled: false
  exclude: []
```

I was wondering if there is a way to set the default directory/folder in that file, e.g. I just want reek to check lib by default, so I'd like something like:

```yml
CheckFolder: lib
IrresponsibleModule:
  enabled: false
  exclude: []
```

And than I run 'reek' instead of 'reek lib'. Is that just silly?  Wrong place perhaps?

Many thanks in advance
