### ISSUE TITLE
Make reek more rails-friendly or add a "rails" mode.

### ISSUE THREAD

**Issue by troessner** [troessner/reek#529]
See #401

**Comment by troessner** [comment]
I'd like to take this one if nobody objects.:)
Let's discuss over the next days in this thread what a "rails-friendly mode" would mean to us.

**Comment by troessner** [comment]
Alrightie, I thought about this today and here's my basic idea:

I'd like to start of with a Sandi Metz quote: "Make the change easy (warning: that might be hard) and then make the change".:)

The basic idea is to **not** implement something like a "rails-mode" but rather to make configurations possible that were not possible before so that basically every user can make up a "rails-mode" for himself (we can of course still give defaults though).

This default configuration I had in mind would be:

```yaml
"app/controllers":
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    enabled: false
"app/helpers":
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    enabled: false
```

A couple of nice benefits we get with this approach:

1.) We don't litter our codebase with things that are rails specific
2.) Every user can generate his own settings with us still being able to give a defaults
3.) We get things like a "Sinatra" mode or similar for free
4.) reek config files get easier since you can kill a couple of birds with one stone (e.g. using broader settings than just excluding things based on method names and so on)

What do you guys think of that?

P.S.: If we go with this approach I'd like to discuss the yaml format first. In an ideal world I'd probably then scope the smells under a top level key "Smells" and the settings from above under a top level key "directory directives". But that makes it pretty uncool. So I'd rather just try to check if a config key is a smell -> if it isn't assume it's a directory -> if it isnt raise ArgumentError.

**Comment by chastell** [comment]
RuboCop uses offence names (their idea of ‘smells’) as top-level keys and `Exclude` subkeys that match paths. We use `exclude` subkeys to match class/method names (which is much more flexible except when you don’t namespace your sub-hierarchies, _right, RAAAAILS?_), but I think it’s more readable to keep the config tree smell-, not path-based:

```YAML
IrresponsibleModule:
  skip:
  - app/controllers/**/*
  - app/helpers/**/*

NestedIterators:
  skip:
  - app/controllers/**/*

UtilityFunction:
  skip:
  - app/helpers/**/*
```

**Comment by troessner** [comment]
>>  but I think it’s more readable to keep the config tree smell-, not path-based:

I disagree for the following reasons:

1.) We have very big reek configs in our production apps. Adding a skip parameter would make it very hard to see what's going on. 
2.) Depending on the subject this would introduce quite some duplication like you already have in your example
3.) It would be a lot harder to explain and showcase a "rails-mode" or a "sinatra-mode" as a side effect of [2]
4.) We already had quite some feature request that would make it necessary to deviate from our "Smell based configuration" approach in any case like #349  and #408

**Comment by chastell** [comment]
Your production experience is definitely a good reason to come up with a solution that would work better in reality than my theoretical examples. :)

Can we use any strings as YAML keys? If yes (given enough quoting), then let’s try paths (or globs?) as keys and see how it works out in practice.

**Comment by troessner** [comment]
>> Can we use any strings as YAML keys?

Yes, keys can be quoted.:)

@mvz what's your take on this?

**Comment by mvz** [comment]
My thoughts:
* I think using paths as keys looks pretty good.
* We can easily use some heuristics to figure out if a key is a path or a smell. Even the following should not be a problem (in the unlikely case of a path called `IrresponsibleModule`), since we can check the nesting:
```
IrresponsibleModule:
  UtilitityFunction:
    enabled: false
```
* Let's add the option to disable all smells in one go for a given path (#349) while we're at it.

**Comment by troessner** [comment]
>> (in the unlikely case of a path called IrresponsibleModule),

:D

>> Let's add the option to disable all smells in one go for a given path (#349) while we're at it.

Good idea!

**Comment by troessner** [comment]
Actually I wanted to look into #548 first, but I believe this must come first because otherwise this will alienate a lot of users. 
Starting with this bad boy now!.:)

**Comment by troessner** [comment]
Now with #593 out in the wild implementing this rails friendly mode should be a breeze since it actually boils down to a sample configuration. So I'd just add a section to our README that says something like "In order to make reek rails-friendly you just have to tweak your configuration like this:"

And then I'd add something like this:

```yaml
"app/controllers":
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    enabled: false
"app/helpers":
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    enabled: false
````

WDYT?
@nTraum do you have any more suggestions regarding my sample config from above?
