### ISSUE TITLE
TooManyStatements top-level config ignored

### ISSUE THREAD

**Issue by codehugger** [troessner/reek#772]
I have this in my config.reek

```yaml
TooManyStatements:
  enabled: true
  max_statements: 15
```

But when I run `bundle exec reek` I get the following output

```
...
[9]:CartsController#destroy has approx 8 statements (TooManyStatements)

**Comment by troessner** [comment]
Can you please post the destroy method as well? And what Reek version?

**Comment by troessner** [comment]
Oh, and how are you loading the config? Seems to me like you put it somewhere where Reek cant find it...

**Comment by codehugger** [comment]
```ruby
```

**Comment by troessner** [comment]
Nope, that works.

```Bash
 ( $ ) cd test/
 ( $ ) ls
config.reek	destroy.rb
( $ ) bundle exec reek destroy.rb
# -> no output
( $ ) rm config.reek
( $ ) bundle exec reek destroy.rb
destroy.rb -- 1 warning:
  [1]:destroy has approx 8 statements (TooManyStatements)
```

With config.reek and destroy.rb containing your code from above.
There's something fishy on your end. Either the config is not loaded for whatever reasons or you're overwriting values. Can you paste the output of:

```Bash
cd $project_root
cat config.reek
bundle exec rake
```

**Comment by codehugger** [comment]
Here are the contents of my config.reek located at the root of my Rails folder. This produces incorrect output and TooManyStatements errors are reported for numbers less than 15.

```yaml
IrresponsibleModule:
  enabled: false

TooManyStatements:
  enabled: true
  max_statements: 15

"app/controllers":                                                                                                                                    
  NestedIterators:
    enabled: false

"app/helpers":
  UtilityFunction:
    enabled: false

exclude_paths:
  - 'vendor'
  - 'db/migrate'
```

I fiddled around with the config.reek file and I managed to pinpoint the error. If I remove the "app/controllers" section I get the correct output for TooManyStatements (all lines report > 15) but of course the NestedIterators now surface for the controllers instead.

```yaml
IrresponsibleModule:
  enabled: false

TooManyStatements:
  max_statements: 15

"app/helpers":
  UtilityFunction:
    enabled: false

exclude_paths:
  - 'vendor'
  - 'db/migrate'
```

So to produce the correct result for reek disabling NestedIterators for the "app/controllers" folder I need to specify IrresponsibleModule twice (once globally and then repeat it for each folder I specify directly). Like so

```yaml
IrresponsibleModule:
  enabled: false

TooManyStatements:
  max_statements: 15

"app/controllers":
  NestedIterators:
    enabled: false
  TooManyStatements:
    max_statements: 15
                                                                                                                              
"app/helpers":
  UtilityFunction:
    enabled: false
    
exclude_paths:
  - 'vendor'
  - 'db/migrate'
```
