### ISSUE TITLE
Reek can't exclude a method in a module?

### ISSUE THREAD

**Issue by andyw8** [troessner/reek#87]
I have a file layout_helper.rb

```
module LayoutHelper
  def title(page_title, show_title = true)
    ...
  end
end
```

and Reek complains with:

```
./app/helpers/layout_helper.rb -- 1 warning:
  LayoutHelper#title has boolean parameter 'show_title' (ControlCouple)
```

I've tried excluding the file with:

```
ControlCouple: 
  enabled: true
  exclude:
  - 'LayoutHelper#title'
```

and

```
ControlCouple: 
  enabled: true
  exclude:
  - !ruby/regexp /LayoutHelper/
```

but neither seem to have any effect.
