### ISSUE TITLE
Documentation for PrimaDonnaMethod exclude option?

### ISSUE THREAD

**Issue by monfresh** [troessner/reek#970]
Hello. I'm trying to exclude a method from the `PrimaDonnaMethod` smell, but it's not being excluded. Here is the output from reek:
```
PrimaDonnaMethod: Devise::TwoFactorAuthenticationController has prima donna method `authenticate_scope!`
```
And here are the different things I tried in my `.reek` file:
```yaml
PrimaDonnaMethod:
  enabled: true
  exclude:
    - "Devise::TwoFactorAuthenticationController#self.authenticate_scope!"
    - "Devise::TwoFactorAuthenticationController#authenticate_scope!"
    - authenticate_scope!
    - authenticate_scope
```
None of these work. What am I doing wrong?

Here is how the method is being called in my app:
```ruby
class Devise::TwoFactorAuthenticationController < DeviseController
  prepend_before_action :authenticate_scope!
  ...
```
